package Loops;

import java.util.Random;
import java.util.Scanner;

public class HeadTailTask {
    public static void main(String[] args) {
        /*
        I want to create a head/tail game(flipping coin) with java codes;
        At the beginning print "Game is started, MAKE a GUESS! HEAD/TAIL " So let the user know the game started
        get users guess as HEAD/TAIL
        compare users guess with your random number 0/1 -->random.nextInt(2);
        if the guess is correct print --> "You are lucky, it is your day today"
        if the guess isn't correct print--> "Sorry,that was not the correct choice!"
        at the end ask user "Do you want to play again? Y/N"
        if the answer is Y--> keep playing (this is your while condition!!!)
        if the answer is N--> print "It's OK, see you next time!"
        */


        //int number = random.nextInt(2);//to store that random number
        // if you want JAVA to give a number smaller than 2 you put 2 in the parenthesis.

        // System.out.println(number);//it will show that random number.
        //it works similar with Scanner class
        // every time you run it, it will give you a new random number every time

        //String guess = number == 0 ? "HEAD" : "TAIL";
        Random random = new Random(); //it's a JAVA class of random number generated by java
        Scanner scanner = new Scanner(System.in);
        String answer2;


        do {
            System.out.println("Game is started, MAKE a GUESS! HEAD/TAIL ");
            String answer = scanner.nextLine();

            int number = random.nextInt(2);
            String guess = number == 0 ? "HEAD" : "TAIL";

            if (answer.equalsIgnoreCase(guess)) {

                System.out.println("You are lucky, it is your day today");
            } else {
                System.out.println("Sorry,that was not the correct choice!");
            }
            System.out.println("Do you want to play again? Y/N");
            answer2 = scanner.nextLine();

        } while (answer2.equalsIgnoreCase("yes"));

        System.out.println("It's OK, see you next time!");
        

    }
}
